vim.opt.autoindent = true
vim.opt.autoread = true
vim.opt.backup = false
vim.opt.completeopt = { "fuzzy", "menuone", "noselect" }
vim.opt.cursorline = true
vim.opt.expandtab = true
vim.opt.foldlevel = 99
vim.opt.foldmethod = "indent"
vim.opt.hidden = true
vim.opt.hlsearch = false
vim.opt.ignorecase = true
vim.opt.incsearch = true
vim.lsp.inlay_hint.enable(true)
vim.opt.isfname:append("@-@")
vim.opt.laststatus = 2
vim.opt.lazyredraw = false
vim.opt.list = false
vim.opt.listchars = {
    tab = "→ ",
    eol = "↲",
    nbsp = "␣",
    trail = "•",
    extends = "⟩",
    precedes = "⟨",
}
vim.opt.mouse = "a"
vim.opt.mousescroll = "ver:1,hor:1"
vim.opt.number = true
vim.opt.winborder = "rounded"
vim.opt.relativenumber = true
vim.opt.ruler = false
vim.opt.scrolloff = 6
vim.opt.shiftwidth = 4
vim.opt.showcmd = true
vim.opt.showcmdloc = 'statusline'
vim.opt.showmode = false
vim.opt.sidescrolloff = 6
vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.softtabstop = 4
vim.opt.spelllang = "en_us"
vim.opt.swapfile = false
vim.opt.synmaxcol = 300
vim.opt.tabstop = 4
vim.opt.termguicolors = true
vim.opt.timeoutlen = 300
vim.opt.title = true
vim.opt.titlestring = "nvim"
vim.opt.ttimeoutlen = 0
vim.opt.undodir = vim.fn.expand("~") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.updatetime = 50
vim.opt.wildmenu = true
vim.opt.wrap = false
