#:schema = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
sort_by = "extension"
linemode = "size"
show_hidden = true
show_symlink = true
mouse_events = ["click", "scroll"]
ratio = [0, 1, 1]

[opener]
edit = [
  { run = 'hx "$@"', desc = "Edit in helix", block = true, for = "unix" },
]
open = [
  { run = 'open "$@"', desc = "Open", for = "macos" },
]
reveal = [
  { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
]
