#!/bin/sh

mkdir -p "$HOME/Developer/Personal/setup/plugins/bin"

for file in $HOME/Developer/Personal/setup/plugins/install-scripts/*; do
    echo "Running plugin install script: $file"
    $file
done
